### ISSUE TITLE
TopMost ViewController?

### ISSUE THREAD

**Issue by JulesMoorhouse** [HarrisonXi/TopmostView#2]
I've been scanning the the demo application, is it possible to get the top most view controller too ?

I don't think it is.
The other pod PPTopMostController have an error is is out of date.

Any help appreciated.

Thanks,

Jules.

**Comment by HarrisonXi** [comment]
I think you need to scan your application's controllers recursively:
1. navController's top controller
2. tabController's selected controller
3. presenting controller
4. splitController
5. some other scenes

It is hard to make a common method for all applications.
